FROM python:3

RUN apt-get update
RUN apt-get install cron -y

#We set an environment variable so that
#Python prints things immediately
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

RUN touch /var/spool/cron/crontabs/root
RUN crontab -l


#We run the Django development server
CMD python manage.py crontab add && service cron start && python manage.py runserver "0.0.0.0:8001"
